import { z } from 'zod';
export declare const PromptRegistryConfiguredSourceV1Schema: any;
export type PromptRegistryConfiguredSourceV1 = z.infer<typeof PromptRegistryConfiguredSourceV1Schema>;
export declare const PromptRegistrySourcesV1Schema: any;
export type PromptRegistrySourcesV1 = z.infer<typeof PromptRegistrySourcesV1Schema>;
export declare const PromptRegistryAdapterDescriptorV1Schema: any;
export type PromptRegistryAdapterDescriptorV1 = z.infer<typeof PromptRegistryAdapterDescriptorV1Schema>;
export declare const PromptRegistrySourceDescriptorV1Schema: any;
export type PromptRegistrySourceDescriptorV1 = z.infer<typeof PromptRegistrySourceDescriptorV1Schema>;
export declare const PromptRegistryItemSummaryV1Schema: any;
export type PromptRegistryItemSummaryV1 = z.infer<typeof PromptRegistryItemSummaryV1Schema>;
export declare const PromptRegistryFetchedItemV1Schema: any;
export type PromptRegistryFetchedItemV1 = z.infer<typeof PromptRegistryFetchedItemV1Schema>;
export declare const PromptRegistryListSourcesRequestV1Schema: any;
export type PromptRegistryListSourcesRequestV1 = z.infer<typeof PromptRegistryListSourcesRequestV1Schema>;
export declare const PromptRegistryScanSourceRequestV1Schema: any;
export type PromptRegistryScanSourceRequestV1 = z.infer<typeof PromptRegistryScanSourceRequestV1Schema>;
export declare const PromptRegistryFetchItemRequestV1Schema: any;
export type PromptRegistryFetchItemRequestV1 = z.infer<typeof PromptRegistryFetchItemRequestV1Schema>;
export declare const PromptRegistryInstallTargetV1Schema: any;
export type PromptRegistryInstallTargetV1 = z.infer<typeof PromptRegistryInstallTargetV1Schema>;
export declare const PromptRegistryInstallRequestV1Schema: any;
export type PromptRegistryInstallRequestV1 = z.infer<typeof PromptRegistryInstallRequestV1Schema>;
export declare const PromptRegistryErrorCodeV1Schema: any;
export type PromptRegistryErrorCodeV1 = z.infer<typeof PromptRegistryErrorCodeV1Schema>;
export declare const PromptRegistryErrorResponseV1Schema: any;
export type PromptRegistryErrorResponseV1 = z.infer<typeof PromptRegistryErrorResponseV1Schema>;
export declare const PromptRegistryListAdaptersResponseV1Schema: any;
export type PromptRegistryListAdaptersResponseV1 = z.infer<typeof PromptRegistryListAdaptersResponseV1Schema>;
export declare const PromptRegistryListSourcesResponseV1Schema: any;
export type PromptRegistryListSourcesResponseV1 = z.infer<typeof PromptRegistryListSourcesResponseV1Schema>;
export declare const PromptRegistryScanSourceResponseV1Schema: any;
export type PromptRegistryScanSourceResponseV1 = z.infer<typeof PromptRegistryScanSourceResponseV1Schema>;
export declare const PromptRegistryFetchItemResponseV1Schema: any;
export type PromptRegistryFetchItemResponseV1 = z.infer<typeof PromptRegistryFetchItemResponseV1Schema>;
export declare const PromptRegistryInstallResponseV1Schema: any;
export type PromptRegistryInstallResponseV1 = z.infer<typeof PromptRegistryInstallResponseV1Schema>;
//# sourceMappingURL=promptRegistriesV1.d.ts.map