import { z } from 'zod';
export declare const PromptAssetScopeV1Schema: any;
export type PromptAssetScopeV1 = z.infer<typeof PromptAssetScopeV1Schema>;
export declare const PromptAssetLibraryKindV1Schema: any;
export type PromptAssetLibraryKindV1 = z.infer<typeof PromptAssetLibraryKindV1Schema>;
export declare const PromptAssetInstallModeV1Schema: any;
export type PromptAssetInstallModeV1 = z.infer<typeof PromptAssetInstallModeV1Schema>;
export declare const PromptAssetSupportsScopeV1Schema: any;
export type PromptAssetSupportsScopeV1 = z.infer<typeof PromptAssetSupportsScopeV1Schema>;
export declare const PromptAssetCapabilitiesV1Schema: any;
export type PromptAssetCapabilitiesV1 = z.infer<typeof PromptAssetCapabilitiesV1Schema>;
export declare const PromptAssetDefaultRootV1Schema: any;
export type PromptAssetDefaultRootV1 = z.infer<typeof PromptAssetDefaultRootV1Schema>;
export declare const PromptAssetExternalRefV1Schema: any;
export type PromptAssetExternalRefV1 = z.infer<typeof PromptAssetExternalRefV1Schema>;
export declare const PromptAssetTypeDescriptorV1Schema: any;
export type PromptAssetTypeDescriptorV1 = z.infer<typeof PromptAssetTypeDescriptorV1Schema>;
export declare const PromptAssetDiscoveryItemV1Schema: any;
export type PromptAssetDiscoveryItemV1 = z.infer<typeof PromptAssetDiscoveryItemV1Schema>;
export declare const PromptAssetBundleRecordV1Schema: any;
export type PromptAssetBundleRecordV1 = z.infer<typeof PromptAssetBundleRecordV1Schema>;
export declare const PromptAssetDocRecordV1Schema: any;
export type PromptAssetDocRecordV1 = z.infer<typeof PromptAssetDocRecordV1Schema>;
export declare const PromptAssetMutationErrorCodeV1Schema: any;
export type PromptAssetMutationErrorCodeV1 = z.infer<typeof PromptAssetMutationErrorCodeV1Schema>;
export declare const PromptAssetMutationPreviewV1Schema: any;
export type PromptAssetMutationPreviewV1 = z.infer<typeof PromptAssetMutationPreviewV1Schema>;
export declare const PromptAssetWriteBundleRequestSchema: any;
export type PromptAssetWriteBundleRequest = z.infer<typeof PromptAssetWriteBundleRequestSchema>;
export declare const PromptAssetWriteDocRequestSchema: any;
export type PromptAssetWriteDocRequest = z.infer<typeof PromptAssetWriteDocRequestSchema>;
export declare const PromptAssetWriteRequestSchema: any;
export type PromptAssetWriteRequest = z.infer<typeof PromptAssetWriteRequestSchema>;
export declare const PromptAssetDeleteRequestSchema: any;
export type PromptAssetDeleteRequest = z.infer<typeof PromptAssetDeleteRequestSchema>;
export declare const PromptAssetReadRequestSchema: any;
export type PromptAssetReadRequest = z.infer<typeof PromptAssetReadRequestSchema>;
export declare const PromptAssetDiscoverRequestSchema: any;
export type PromptAssetDiscoverRequest = z.infer<typeof PromptAssetDiscoverRequestSchema>;
export declare const PromptAssetMutationSuccessResponseV1Schema: any;
export declare const PromptAssetMutationErrorResponseV1Schema: any;
export declare const PromptAssetMutationResponseV1Schema: any;
export type PromptAssetMutationResponseV1 = z.infer<typeof PromptAssetMutationResponseV1Schema>;
export declare const PromptAssetListTypesResponseV1Schema: any;
export type PromptAssetListTypesResponseV1 = z.infer<typeof PromptAssetListTypesResponseV1Schema>;
export declare const PromptAssetDiscoverResponseV1Schema: any;
export type PromptAssetDiscoverResponseV1 = z.infer<typeof PromptAssetDiscoverResponseV1Schema>;
export declare const PromptAssetReadResponseV1Schema: any;
export type PromptAssetReadResponseV1 = z.infer<typeof PromptAssetReadResponseV1Schema>;
//# sourceMappingURL=promptAssetsV1.d.ts.map