import { z } from 'zod';
export declare const SESSION_RUNNER_RUNTIME_STATE_FIELD_ID: "runtime.sessionRunner";
export declare const SESSION_RUNNER_RESTART_MODES_V1: readonly ["if_stale", "force_current_cli"];
export declare const SessionRunnerRestartModeV1Schema: any;
export type SessionRunnerRestartModeV1 = z.infer<typeof SessionRunnerRestartModeV1Schema>;
export declare const SESSION_RUNNER_RESTART_REASONS_V1: readonly ["ui_stale_runner_banner", "daemon_restart_session_runners", "daemon_restart_session_runners_command", "self_update_interactive_prompt", "doctor_repair", "restart_session_runners_on_update_config", "daemon_dist_generation_rollout"];
export declare const SessionRunnerRestartReasonV1Schema: any;
export type SessionRunnerRestartReasonV1 = z.infer<typeof SessionRunnerRestartReasonV1Schema>;
export declare const SESSION_RUNNER_RESTART_DISABLED_REASONS: readonly ["not_daemon_started", "not_remote_started", "not_active", "no_tracked_process", "missing_resume_identity", "missing_spawn_options", "missing_credentials", "unsupported_backend", "turn_in_progress", "approval_pending", "terminal_detached", "terminal_host_attached", "non_destructive_refresh_unsupported", "windows_hosted_runner", "restart_already_running", "current_entrypoint_unknown", "runner_entrypoint_unknown", "runner_generation_unattested", "unsupported_daemon_version"];
export declare const SessionRunnerRestartDisabledReasonSchema: any;
export type SessionRunnerRestartDisabledReason = z.infer<typeof SessionRunnerRestartDisabledReasonSchema>;
export declare const SESSION_RUNNER_RESTART_STATUSES_V1: readonly ["restarted", "already_current", "dry_run_restartable", "not_found", "not_tracked", "not_daemon_started", "runner_not_active", "version_unknown", "runner_identity_changed", "busy", "missing_resume_snapshot", "missing_spawn_options", "unsupported_daemon", "ineligible", "stop_failed", "spawn_failed", "partial_failure"];
export declare const RestartSessionRunnerStatusV1Schema: any;
export type RestartSessionRunnerStatusV1 = z.infer<typeof RestartSessionRunnerStatusV1Schema>;
export declare const RestartSessionRunnerRequestV1Schema: any;
export type RestartSessionRunnerRequestV1 = z.infer<typeof RestartSessionRunnerRequestV1Schema>;
export declare const RestartAllSessionRunnersRequestV1Schema: any;
export type RestartAllSessionRunnersRequestV1 = z.infer<typeof RestartAllSessionRunnersRequestV1Schema>;
export declare const RestartSessionRunnerResultV1Schema: any;
export type RestartSessionRunnerResultV1 = z.infer<typeof RestartSessionRunnerResultV1Schema>;
export declare const RestartAllSessionRunnersResultV1Schema: any;
export type RestartAllSessionRunnersResultV1 = z.infer<typeof RestartAllSessionRunnersResultV1Schema>;
export declare const SessionRunnerEntrypointSourceV1Schema: any;
export type SessionRunnerEntrypointSourceV1 = z.infer<typeof SessionRunnerEntrypointSourceV1Schema>;
export declare const SessionRunnerDaemonEntrypointSourceV1Schema: any;
export type SessionRunnerDaemonEntrypointSourceV1 = z.infer<typeof SessionRunnerDaemonEntrypointSourceV1Schema>;
export declare const SessionRunnerStartedByV1Schema: any;
export type SessionRunnerStartedByV1 = z.infer<typeof SessionRunnerStartedByV1Schema>;
export declare const SessionRunnerStartingModeV1Schema: any;
export type SessionRunnerStartingModeV1 = z.infer<typeof SessionRunnerStartingModeV1Schema>;
export declare const SessionRunnerVersionStateV1Schema: any;
export type SessionRunnerVersionStateV1 = z.infer<typeof SessionRunnerVersionStateV1Schema>;
export declare const SessionRunnerRuntimeStatusSourceV1Schema: any;
export type SessionRunnerRuntimeStatusSourceV1 = z.infer<typeof SessionRunnerRuntimeStatusSourceV1Schema>;
export declare const SessionRunnerRuntimeStateV1Schema: any;
export type SessionRunnerRuntimeStateV1 = z.infer<typeof SessionRunnerRuntimeStateV1Schema>;
export declare const SessionRunnerStatusGetRequestV1Schema: any;
export type SessionRunnerStatusGetRequestV1 = z.infer<typeof SessionRunnerStatusGetRequestV1Schema>;
//# sourceMappingURL=contract.d.ts.map