/** Maps file names to the Prism grammar id we load for them. */

const BY_EXTENSION: Record<string, string> = {
    ts: 'typescript',
    tsx: 'tsx',
    mts: 'typescript',
    cts: 'typescript',
    js: 'javascript',
    jsx: 'jsx',
    mjs: 'javascript',
    cjs: 'javascript',
    json: 'json',
    jsonc: 'json',
    json5: 'json',
    py: 'python',
    pyi: 'python',
    rb: 'ruby',
    go: 'go',
    rs: 'rust',
    java: 'java',
    kt: 'kotlin',
    kts: 'kotlin',
    swift: 'swift',
    m: 'objectivec',
    mm: 'objectivec',
    c: 'c',
    h: 'c',
    cc: 'cpp',
    cpp: 'cpp',
    cxx: 'cpp',
    hpp: 'cpp',
    cs: 'csharp',
    php: 'php',
    sh: 'bash',
    bash: 'bash',
    zsh: 'bash',
    fish: 'bash',
    ps1: 'powershell',
    sql: 'sql',
    css: 'css',
    scss: 'scss',
    sass: 'scss',
    less: 'less',
    html: 'markup',
    htm: 'markup',
    xml: 'markup',
    svg: 'markup',
    vue: 'markup',
    md: 'markdown',
    mdx: 'markdown',
    yml: 'yaml',
    yaml: 'yaml',
    toml: 'toml',
    ini: 'ini',
    cfg: 'ini',
    env: 'bash',
    dart: 'dart',
    ex: 'elixir',
    exs: 'elixir',
    erl: 'erlang',
    hs: 'haskell',
    lua: 'lua',
    r: 'r',
    scala: 'scala',
    graphql: 'graphql',
    gql: 'graphql',
    proto: 'protobuf',
    tf: 'hcl',
    hcl: 'hcl',
    zig: 'zig',
    nim: 'nim',
    pl: 'perl',
    diff: 'diff',
    patch: 'diff',
};

const BY_FILENAME: Record<string, string> = {
    dockerfile: 'docker',
    makefile: 'makefile',
    'cmakelists.txt': 'cmake',
    gemfile: 'ruby',
    rakefile: 'ruby',
    '.gitignore': 'ignore',
    '.npmrc': 'ini',
    '.editorconfig': 'ini',
};

export function detectLanguage(path: string | null | undefined): string | null {
    if (!path) return null;
    const name = path.split('/').pop()!.toLowerCase();
    if (BY_FILENAME[name]) return BY_FILENAME[name];
    const dot = name.lastIndexOf('.');
    if (dot === -1 || dot === name.length - 1) return null;
    return BY_EXTENSION[name.slice(dot + 1)] ?? null;
}
