import { z } from 'zod';
export declare const DaemonTerminalErrorCodeSchema: any;
export type DaemonTerminalErrorCode = z.infer<typeof DaemonTerminalErrorCodeSchema>;
export declare const DaemonTerminalErrorSchema: any;
export type DaemonTerminalError = z.infer<typeof DaemonTerminalErrorSchema>;
export declare const DaemonTerminalLaunchIntentSchema: any;
export type DaemonTerminalLaunchIntent = z.infer<typeof DaemonTerminalLaunchIntentSchema>;
export declare const DaemonTerminalEnsureRequestSchema: any;
export type DaemonTerminalEnsureRequest = z.infer<typeof DaemonTerminalEnsureRequestSchema>;
export declare const DaemonTerminalEnsureResponseSchema: any;
export type DaemonTerminalEnsureResponse = z.infer<typeof DaemonTerminalEnsureResponseSchema>;
export declare const DaemonTerminalStreamReadRequestSchema: any;
export type DaemonTerminalStreamReadRequest = z.infer<typeof DaemonTerminalStreamReadRequestSchema>;
export declare const DaemonTerminalStreamEventDataSchema: any;
export type DaemonTerminalStreamEventData = z.infer<typeof DaemonTerminalStreamEventDataSchema>;
export declare const DaemonTerminalStreamEventUrlSchema: any;
export type DaemonTerminalStreamEventUrl = z.infer<typeof DaemonTerminalStreamEventUrlSchema>;
export declare const DaemonTerminalStreamEventGapSchema: any;
export type DaemonTerminalStreamEventGap = z.infer<typeof DaemonTerminalStreamEventGapSchema>;
export declare const DaemonTerminalStreamEventExitSchema: any;
export type DaemonTerminalStreamEventExit = z.infer<typeof DaemonTerminalStreamEventExitSchema>;
export declare const DaemonTerminalStreamEventSchema: any;
export type DaemonTerminalStreamEvent = z.infer<typeof DaemonTerminalStreamEventSchema>;
export declare const DaemonTerminalStreamReadResponseSchema: any;
export type DaemonTerminalStreamReadResponse = z.infer<typeof DaemonTerminalStreamReadResponseSchema>;
export declare const DaemonTerminalInputRequestSchema: any;
export type DaemonTerminalInputRequest = z.infer<typeof DaemonTerminalInputRequestSchema>;
export declare const DaemonTerminalInputResponseSchema: any;
export type DaemonTerminalInputResponse = z.infer<typeof DaemonTerminalInputResponseSchema>;
export declare const DaemonTerminalResizeRequestSchema: any;
export type DaemonTerminalResizeRequest = z.infer<typeof DaemonTerminalResizeRequestSchema>;
export declare const DaemonTerminalResizeResponseSchema: any;
export type DaemonTerminalResizeResponse = z.infer<typeof DaemonTerminalResizeResponseSchema>;
export declare const DaemonTerminalCloseRequestSchema: any;
export type DaemonTerminalCloseRequest = z.infer<typeof DaemonTerminalCloseRequestSchema>;
export declare const DaemonTerminalCloseResponseSchema: any;
export type DaemonTerminalCloseResponse = z.infer<typeof DaemonTerminalCloseResponseSchema>;
export declare const DaemonTerminalRestartRequestSchema: any;
export type DaemonTerminalRestartRequest = z.infer<typeof DaemonTerminalRestartRequestSchema>;
export declare const DaemonTerminalRestartResponseSchema: any;
export type DaemonTerminalRestartResponse = z.infer<typeof DaemonTerminalRestartResponseSchema>;
//# sourceMappingURL=daemonTerminal.d.ts.map