import { z } from 'zod';
import { SessionHandoffProgressCheckpointSchema, SessionHandoffProgressWarningCodeSchema, SessionHandoffStatusSchema, SessionHandoffWorkspacePreflightSummarySchema } from './handoffStatus.js';
import { TransferChunkEnvelopeSchema, TransferEndpointCandidateSchema } from '../../machineTransfer/transferStream.js';
export declare const SessionHandoffWorkspaceTransferSchema: any;
export type SessionHandoffWorkspaceTransfer = z.infer<typeof SessionHandoffWorkspaceTransferSchema>;
declare const SessionHandoffProviderBundleTransferPublicationSchema: any;
export type SessionHandoffProviderBundleTransferPublication = z.infer<typeof SessionHandoffProviderBundleTransferPublicationSchema>;
declare const SessionHandoffWorkspaceReplicationManifestTransferPublicationSchema: any;
export type SessionHandoffWorkspaceReplicationManifestTransferPublication = z.infer<typeof SessionHandoffWorkspaceReplicationManifestTransferPublicationSchema>;
export declare const SessionHandoffMetadataV2Schema: any;
export type SessionHandoffMetadataV2 = z.infer<typeof SessionHandoffMetadataV2Schema>;
declare const SessionHandoffResumePlanSchema: any;
export type SessionHandoffResumePlan = z.infer<typeof SessionHandoffResumePlanSchema>;
export declare const SessionHandoffStartRequestSchema: any;
export type SessionHandoffStartRequest = z.infer<typeof SessionHandoffStartRequestSchema>;
export declare const SessionHandoffPrepareTargetRequestSchema: any;
export type SessionHandoffPrepareTargetRequest = z.infer<typeof SessionHandoffPrepareTargetRequestSchema>;
export declare const SessionHandoffPrepareTargetRequestV2Schema: any;
export type SessionHandoffPrepareTargetRequestV2 = z.infer<typeof SessionHandoffPrepareTargetRequestV2Schema>;
export declare const SessionHandoffPrepareTargetResultGetRequestSchema: any;
export type SessionHandoffPrepareTargetResultGetRequest = z.infer<typeof SessionHandoffPrepareTargetResultGetRequestSchema>;
export declare const SessionHandoffPrepareTargetResultGetRequestV2Schema: any;
export type SessionHandoffPrepareTargetResultGetRequestV2 = z.infer<typeof SessionHandoffPrepareTargetResultGetRequestV2Schema>;
export declare const SessionHandoffCommitRequestSchema: any;
export type SessionHandoffCommitRequest = z.infer<typeof SessionHandoffCommitRequestSchema>;
export declare const SessionHandoffAbortRequestSchema: any;
export type SessionHandoffAbortRequest = z.infer<typeof SessionHandoffAbortRequestSchema>;
export declare const SessionHandoffAbortRequestV2Schema: any;
export type SessionHandoffAbortRequestV2 = z.infer<typeof SessionHandoffAbortRequestV2Schema>;
export declare const SessionHandoffTargetResumeRequestV2Schema: any;
export type SessionHandoffTargetResumeRequestV2 = z.infer<typeof SessionHandoffTargetResumeRequestV2Schema>;
export declare const SessionHandoffTargetResumeResponseV2Schema: any;
export type SessionHandoffTargetResumeResponseV2 = z.infer<typeof SessionHandoffTargetResumeResponseV2Schema>;
export declare const SessionHandoffTargetConfirmRequestV2Schema: any;
export type SessionHandoffTargetConfirmRequestV2 = z.infer<typeof SessionHandoffTargetConfirmRequestV2Schema>;
export declare const SessionHandoffCommitRequestV2Schema: any;
export type SessionHandoffCommitRequestV2 = z.infer<typeof SessionHandoffCommitRequestV2Schema>;
export declare const SessionHandoffStartResponseSchema: any;
export type SessionHandoffStartResponse = z.infer<typeof SessionHandoffStartResponseSchema>;
export declare const SessionHandoffPrepareTargetResponseSchema: any;
export type SessionHandoffPrepareTargetResponse = z.infer<typeof SessionHandoffPrepareTargetResponseSchema>;
export declare const SessionHandoffPrepareTargetResultGetResponseSchema: any;
export type SessionHandoffPrepareTargetResultGetResponse = z.infer<typeof SessionHandoffPrepareTargetResultGetResponseSchema>;
export declare const SessionHandoffCommitResponseSchema: any;
export type SessionHandoffCommitResponse = z.infer<typeof SessionHandoffCommitResponseSchema>;
export declare const SessionHandoffTargetCleanupSchema: any;
export type SessionHandoffTargetCleanup = z.infer<typeof SessionHandoffTargetCleanupSchema>;
export declare const SessionHandoffAbortResponseSchema: any;
export type SessionHandoffAbortResponse = z.infer<typeof SessionHandoffAbortResponseSchema>;
export declare const SessionHandoffAbortResponseV2Schema: any;
export type SessionHandoffAbortResponseV2 = z.infer<typeof SessionHandoffAbortResponseV2Schema>;
export declare const SessionHandoffStatusGetRequestSchema: any;
export type SessionHandoffStatusGetRequest = z.infer<typeof SessionHandoffStatusGetRequestSchema>;
export { SessionHandoffProgressCheckpointSchema, SessionHandoffProgressWarningCodeSchema, SessionHandoffStatusSchema, SessionHandoffWorkspacePreflightSummarySchema, TransferChunkEnvelopeSchema, TransferEndpointCandidateSchema, };
//# sourceMappingURL=handoffSchemas.d.ts.map