import { z } from 'zod';
export declare const CONNECTED_SERVICE_UX_DIAGNOSTIC_CODES: {
    readonly providerSessionStateUnavailableForResume: "provider_session_state_unavailable_for_resume";
    readonly connectedServiceMaterializationIdentityMissing: "connected_service_materialization_identity_missing";
    readonly resumeReachabilityInputsMissing: "resume_reachability_inputs_missing";
    readonly metadataUpdateFailed: "metadata_update_failed";
    readonly noEligibleGroupMember: "no_eligible_group_member";
    readonly recoveryRetryScheduled: "recovery_retry_scheduled";
    readonly recoveryDeadLettered: "recovery_dead_lettered";
    readonly runtimeAuthRecoverySuperseded: "runtime_auth_recovery_superseded";
    readonly runtimeAuthGenerationStale: "runtime_auth_generation_stale";
    readonly hotApplyUnavailable: "hot_apply_unavailable";
    readonly appServerUnavailable: "app_server_unavailable";
    readonly providerAccountAdoptionMismatch: "provider_account_adoption_mismatch";
    readonly providerAccountIdentityUnverified: "provider_account_identity_unverified";
    readonly postSwitchVerificationFailed: "post_switch_verification_failed";
    readonly quotaSnapshotStale: "quota_snapshot_stale";
    readonly quotaFetchDisabled: "quota_fetch_disabled";
    readonly quotaFetchBackoff: "quota_fetch_backoff";
    readonly authSurfaceWeaklyVerified: "auth_surface_weakly_verified";
    readonly connectedServiceRestartRequested: "connected_service_restart_requested";
    readonly connectedServiceCredentialReconnectRequired: "connected_service_credential_reconnect_required";
    readonly claudeSubscriptionMissingClaudeCodeScope: "claude_subscription_missing_claude_code_scope";
    readonly claudeSubscriptionNativeAuthMaterializationFailed: "claude_subscription_native_auth_materialization_failed";
    readonly claudeSubscriptionSetupTokenNotSupportedForUnified: "claude_subscription_setup_token_not_supported_for_unified";
};
export declare const ConnectedServiceUxDiagnosticCodeV1Schema: any;
export type ConnectedServiceUxDiagnosticCodeV1 = z.infer<typeof ConnectedServiceUxDiagnosticCodeV1Schema>;
export declare const ConnectedServiceUxDiagnosticFailurePhaseV1Schema: any;
export type ConnectedServiceUxDiagnosticFailurePhaseV1 = z.infer<typeof ConnectedServiceUxDiagnosticFailurePhaseV1Schema>;
export declare const ConnectedServiceUxDiagnosticSourceV1Schema: any;
export type ConnectedServiceUxDiagnosticSourceV1 = z.infer<typeof ConnectedServiceUxDiagnosticSourceV1Schema>;
export declare const CONNECTED_SERVICE_UX_DIAGNOSTIC_ACTIONS: {
    readonly retry: "retry";
    readonly startFreshUnderSelectedAccount: "start_fresh_under_selected_account";
    readonly resumeCurrentAccount: "resume_current_account";
    readonly openConnectedAccounts: "open_connected_accounts";
    readonly reconnectProfile: "reconnect_profile";
    readonly enableStateSharing: "enable_state_sharing";
    readonly viewLatestFork: "view_latest_fork";
    readonly viewNativeFork: "view_native_fork";
    readonly dismiss: "dismiss";
};
export declare const ConnectedServiceUxDiagnosticSuggestedActionV1Schema: any;
export type ConnectedServiceUxDiagnosticSuggestedActionV1 = z.infer<typeof ConnectedServiceUxDiagnosticSuggestedActionV1Schema>;
export declare const CONNECTED_SERVICE_UX_DIAGNOSTIC_MAX_DIAGNOSTIC_KEYS = 16;
export declare const CONNECTED_SERVICE_UX_DIAGNOSTIC_MAX_DIAGNOSTIC_KEY_LENGTH = 64;
export declare const CONNECTED_SERVICE_UX_DIAGNOSTIC_MAX_STRING_LENGTH = 512;
export declare const ConnectedServiceUxDiagnosticV1Schema: any;
export type ConnectedServiceUxDiagnosticV1 = z.infer<typeof ConnectedServiceUxDiagnosticV1Schema>;
export declare function normalizeConnectedServiceUxDiagnosticV1(value: unknown): ConnectedServiceUxDiagnosticV1 | null;
export declare function isConnectedServiceUxDiagnosticV1(value: unknown): value is ConnectedServiceUxDiagnosticV1;
//# sourceMappingURL=connectedServiceUxDiagnostics.d.ts.map