import { z } from 'zod';
export declare const SetSessionPinRequestSchema: any;
export type SetSessionPinRequest = z.infer<typeof SetSessionPinRequestSchema>;
export declare const SetSessionPinResponseSchema: any;
export type SetSessionPinResponse = z.infer<typeof SetSessionPinResponseSchema>;
export declare const ReorderSessionOrganizationRequestSchema: any;
export type ReorderSessionOrganizationRequest = z.infer<typeof ReorderSessionOrganizationRequestSchema>;
export declare const ReorderSessionOrganizationResponseSchema: any;
export type ReorderSessionOrganizationResponse = z.infer<typeof ReorderSessionOrganizationResponseSchema>;
export declare const CreateOrUpdateSessionOrganizationFolderRequestSchema: any;
export type CreateOrUpdateSessionOrganizationFolderRequest = z.infer<typeof CreateOrUpdateSessionOrganizationFolderRequestSchema>;
export declare const CreateOrUpdateSessionOrganizationFolderResponseSchema: any;
export type CreateOrUpdateSessionOrganizationFolderResponse = z.infer<typeof CreateOrUpdateSessionOrganizationFolderResponseSchema>;
export declare const DeleteSessionOrganizationFolderRequestSchema: any;
export type DeleteSessionOrganizationFolderRequest = z.infer<typeof DeleteSessionOrganizationFolderRequestSchema>;
export declare const DeleteSessionOrganizationFolderResponseSchema: any;
export type DeleteSessionOrganizationFolderResponse = z.infer<typeof DeleteSessionOrganizationFolderResponseSchema>;
export declare const SetSessionFolderAssignmentRequestSchema: any;
export type SetSessionFolderAssignmentRequest = z.infer<typeof SetSessionFolderAssignmentRequestSchema>;
export declare const SetSessionFolderAssignmentResponseSchema: any;
export type SetSessionFolderAssignmentResponse = z.infer<typeof SetSessionFolderAssignmentResponseSchema>;
export declare const MoveSessionFolderAssignmentsRequestSchema: any;
export type MoveSessionFolderAssignmentsRequest = z.infer<typeof MoveSessionFolderAssignmentsRequestSchema>;
export declare const MoveSessionFolderAssignmentsResponseSchema: any;
export type MoveSessionFolderAssignmentsResponse = z.infer<typeof MoveSessionFolderAssignmentsResponseSchema>;
export declare const SessionFolderAssignmentListRequestSchema: any;
export type SessionFolderAssignmentListRequest = z.infer<typeof SessionFolderAssignmentListRequestSchema>;
export declare const SessionFolderAssignmentListResponseSchema: any;
export type SessionFolderAssignmentListResponse = z.infer<typeof SessionFolderAssignmentListResponseSchema>;
export declare const CreateOrUpdateSessionOrganizationTagRequestSchema: any;
export type CreateOrUpdateSessionOrganizationTagRequest = z.infer<typeof CreateOrUpdateSessionOrganizationTagRequestSchema>;
export declare const CreateOrUpdateSessionOrganizationTagResponseSchema: any;
export type CreateOrUpdateSessionOrganizationTagResponse = z.infer<typeof CreateOrUpdateSessionOrganizationTagResponseSchema>;
export declare const DeleteSessionOrganizationTagRequestSchema: any;
export type DeleteSessionOrganizationTagRequest = z.infer<typeof DeleteSessionOrganizationTagRequestSchema>;
export declare const DeleteSessionOrganizationTagResponseSchema: any;
export type DeleteSessionOrganizationTagResponse = z.infer<typeof DeleteSessionOrganizationTagResponseSchema>;
export declare const SetSessionTagAssignmentsRequestSchema: any;
export type SetSessionTagAssignmentsRequest = z.infer<typeof SetSessionTagAssignmentsRequestSchema>;
export declare const SetSessionTagAssignmentsResponseSchema: any;
export type SetSessionTagAssignmentsResponse = z.infer<typeof SetSessionTagAssignmentsResponseSchema>;
export declare const UpsertSessionOrganizationLabelRequestSchema: any;
export type UpsertSessionOrganizationLabelRequest = z.infer<typeof UpsertSessionOrganizationLabelRequestSchema>;
export declare const UpsertSessionOrganizationLabelResponseSchema: any;
export type UpsertSessionOrganizationLabelResponse = z.infer<typeof UpsertSessionOrganizationLabelResponseSchema>;
export declare const DeleteSessionOrganizationLabelRequestSchema: any;
export type DeleteSessionOrganizationLabelRequest = z.infer<typeof DeleteSessionOrganizationLabelRequestSchema>;
export declare const DeleteSessionOrganizationLabelResponseSchema: any;
export type DeleteSessionOrganizationLabelResponse = z.infer<typeof DeleteSessionOrganizationLabelResponseSchema>;
export declare const ImportLegacySessionOrganizationRequestSchema: any;
export type ImportLegacySessionOrganizationRequest = z.infer<typeof ImportLegacySessionOrganizationRequestSchema>;
export declare const ImportLegacySessionOrganizationResponseSchema: any;
export type ImportLegacySessionOrganizationResponse = z.infer<typeof ImportLegacySessionOrganizationResponseSchema>;
//# sourceMappingURL=mutations.d.ts.map