export const FEATURE_ENV_KEYS = Object.freeze({
  automationsEnabled: 'KAIWU_FEATURE_AUTOMATIONS__ENABLED',

  bugReportsEnabled: 'KAIWU_FEATURE_BUG_REPORTS__ENABLED',
  bugReportsProviderUrl: 'KAIWU_FEATURE_BUG_REPORTS__PROVIDER_URL',
  bugReportsDefaultIncludeDiagnostics: 'KAIWU_FEATURE_BUG_REPORTS__DEFAULT_INCLUDE_DIAGNOSTICS',
  bugReportsMaxArtifactBytes: 'KAIWU_FEATURE_BUG_REPORTS__MAX_ARTIFACT_BYTES',
  bugReportsUploadTimeoutMs: 'KAIWU_FEATURE_BUG_REPORTS__UPLOAD_TIMEOUT_MS',
  bugReportsAcceptedArtifactKinds: 'KAIWU_FEATURE_BUG_REPORTS__ACCEPTED_ARTIFACT_KINDS',
  bugReportsContextWindowMs: 'KAIWU_FEATURE_BUG_REPORTS__CONTEXT_WINDOW_MS',

  voiceEnabled: 'KAIWU_FEATURE_VOICE__ENABLED',
  voiceRequireSubscription: 'KAIWU_FEATURE_VOICE__REQUIRE_SUBSCRIPTION',

  connectedServicesEnabled: 'KAIWU_FEATURE_CONNECTED_SERVICES__ENABLED',
  connectedServicesQuotasEnabled: 'KAIWU_FEATURE_CONNECTED_SERVICES_QUOTAS__ENABLED',
  connectedServicesAccountGroupsEnabled: 'KAIWU_FEATURE_CONNECTED_SERVICES_ACCOUNT_GROUPS__ENABLED',
  connectedServicesAccountFallbackEnabled: 'KAIWU_FEATURE_CONNECTED_SERVICES_ACCOUNT_FALLBACK__ENABLED',

  channelBridgesEnabled: 'KAIWU_FEATURE_CHANNEL_BRIDGES__ENABLED',
  channelBridgesTelegramEnabled: 'KAIWU_FEATURE_CHANNEL_BRIDGES_TELEGRAM__ENABLED',

  updatesOtaEnabled: 'KAIWU_FEATURE_UPDATES_OTA__ENABLED',

  attachmentsUploadsEnabled: 'KAIWU_FEATURE_ATTACHMENTS_UPLOADS__ENABLED',

  petsCompanionEnabled: 'KAIWU_FEATURE_PETS_COMPANION__ENABLED',
  petsSyncEnabled: 'KAIWU_FEATURE_PETS_SYNC__ENABLED',
  petsSyncMaxManifestBytes: 'KAIWU_FEATURE_PETS_SYNC__MAX_MANIFEST_BYTES',
  petsSyncMaxCanonicalSpritesheetBytes: 'KAIWU_FEATURE_PETS_SYNC__MAX_CANONICAL_SPRITESHEET_BYTES',
  petsSyncMaxCanonicalPackageBytes: 'KAIWU_FEATURE_PETS_SYNC__MAX_CANONICAL_PACKAGE_BYTES',
  petsSyncMaxImportedPetsPerAccount: 'KAIWU_FEATURE_PETS_SYNC__MAX_IMPORTED_PETS_PER_ACCOUNT',
  petsSyncMaxImportedPetBytesPerAccount: 'KAIWU_FEATURE_PETS_SYNC__MAX_IMPORTED_PET_BYTES_PER_ACCOUNT',
  petsSyncEncryptedCustomPetSyncPolicy: 'KAIWU_FEATURE_PETS_SYNC__ENCRYPTED_CUSTOM_PET_SYNC_POLICY',

  sessionsHandoffEnabled: 'KAIWU_FEATURE_SESSIONS_HANDOFF__ENABLED',
  sessionsUsageLimitRecoveryEnabled: 'KAIWU_FEATURE_SESSIONS_USAGE_LIMIT_RECOVERY__ENABLED',
  sessionsAgentSwitchingEnabled: 'KAIWU_FEATURE_SESSIONS_AGENT_SWITCHING__ENABLED',
  sessionsFoldersEnabled: 'KAIWU_FEATURE_SESSIONS_FOLDERS__ENABLED',
  sessionsDraftsEnabled: 'KAIWU_FEATURE_SESSIONS_DRAFTS__ENABLED',
  machinesTransferDirectPeerEnabled: 'KAIWU_FEATURE_MACHINES_TRANSFER_DIRECT_PEER__ENABLED',
  machinesTransferServerRoutedEnabled: 'KAIWU_FEATURE_MACHINES_TRANSFER_SERVER_ROUTED__ENABLED',
  machinesTransferServerRoutedMaxBytes: 'KAIWU_FEATURE_MACHINES_TRANSFER_SERVER_ROUTED__MAX_BYTES',
  machinesTransferServerRoutedMaxActiveTransfersPerSocket:
    'KAIWU_FEATURE_MACHINES_TRANSFER_SERVER_ROUTED__MAX_ACTIVE_TRANSFERS_PER_SOCKET',

  terminalEmbeddedPtyEnabled: 'KAIWU_FEATURE_TERMINAL_EMBEDDED_PTY__ENABLED',

  socialFriendsEnabled: 'KAIWU_FEATURE_SOCIAL_FRIENDS__ENABLED',
  socialFriendsAllowUsername: 'KAIWU_FEATURE_SOCIAL_FRIENDS__ALLOW_USERNAME',
  socialFriendsIdentityProvider: 'KAIWU_FEATURE_SOCIAL_FRIENDS__IDENTITY_PROVIDER',

  authRecoveryProviderResetEnabled: 'KAIWU_FEATURE_AUTH_RECOVERY__PROVIDER_RESET_ENABLED',
  authLoginKeyChallengeEnabled: 'KAIWU_FEATURE_AUTH_LOGIN__KEY_CHALLENGE_ENABLED',
  authPairingDesktopQrMobileScanEnabled: 'KAIWU_FEATURE_AUTH_PAIRING__DESKTOP_QR_MOBILE_SCAN_ENABLED',
  authUiAutoRedirectEnabled: 'KAIWU_FEATURE_AUTH_UI__AUTO_REDIRECT_ENABLED',
  authUiAutoRedirectProviderId: 'KAIWU_FEATURE_AUTH_UI__AUTO_REDIRECT_PROVIDER_ID',
  authUiRecoveryKeyReminderEnabled: 'KAIWU_FEATURE_AUTH_UI__RECOVERY_KEY_REMINDER_ENABLED',
  authMtlsEnabled: 'KAIWU_FEATURE_AUTH_MTLS__ENABLED',
  authMtlsMode: 'KAIWU_FEATURE_AUTH_MTLS__MODE',
  authMtlsAutoProvision: 'KAIWU_FEATURE_AUTH_MTLS__AUTO_PROVISION',
  authMtlsTrustForwardedHeaders: 'KAIWU_FEATURE_AUTH_MTLS__TRUST_FORWARDED_HEADERS',
  authMtlsIdentitySource: 'KAIWU_FEATURE_AUTH_MTLS__IDENTITY_SOURCE',
  authMtlsAllowedEmailDomains: 'KAIWU_FEATURE_AUTH_MTLS__ALLOWED_EMAIL_DOMAINS',
  authMtlsAllowedIssuers: 'KAIWU_FEATURE_AUTH_MTLS__ALLOWED_ISSUERS',
  authMtlsForwardedEmailHeader: 'KAIWU_FEATURE_AUTH_MTLS__FORWARDED_EMAIL_HEADER',
  authMtlsForwardedUpnHeader: 'KAIWU_FEATURE_AUTH_MTLS__FORWARDED_UPN_HEADER',
  authMtlsForwardedSubjectHeader: 'KAIWU_FEATURE_AUTH_MTLS__FORWARDED_SUBJECT_HEADER',
  authMtlsForwardedFingerprintHeader: 'KAIWU_FEATURE_AUTH_MTLS__FORWARDED_FINGERPRINT_HEADER',
  authMtlsForwardedIssuerHeader: 'KAIWU_FEATURE_AUTH_MTLS__FORWARDED_ISSUER_HEADER',
  authMtlsReturnToAllowPrefixes: 'KAIWU_FEATURE_AUTH_MTLS__RETURN_TO_ALLOW_PREFIXES',
  authMtlsClaimTtlSeconds: 'KAIWU_FEATURE_AUTH_MTLS__CLAIM_TTL_SECONDS',

  authOauthKeylessEnabled: 'KAIWU_FEATURE_AUTH_OAUTH__KEYLESS_ENABLED',
  authOauthKeylessProviders: 'KAIWU_FEATURE_AUTH_OAUTH__KEYLESS_PROVIDERS',
  authOauthKeylessAutoProvision: 'KAIWU_FEATURE_AUTH_OAUTH__KEYLESS_AUTO_PROVISION',

  encryptionStoragePolicy: 'KAIWU_FEATURE_ENCRYPTION__STORAGE_POLICY',
  encryptionAllowAccountOptOut: 'KAIWU_FEATURE_ENCRYPTION__ALLOW_ACCOUNT_OPTOUT',
  encryptionDefaultAccountMode: 'KAIWU_FEATURE_ENCRYPTION__DEFAULT_ACCOUNT_MODE',
  encryptionPlainAccountSettingsAtRest: 'KAIWU_FEATURE_ENCRYPTION__PLAIN_ACCOUNT_SETTINGS_AT_REST',
  encryptionPlainAccountCredentialsAtRest: 'KAIWU_FEATURE_ENCRYPTION__PLAIN_ACCOUNT_CREDENTIALS_AT_REST',

  e2eeKeylessAccountsEnabled: 'KAIWU_FEATURE_E2EE__KEYLESS_ACCOUNTS_ENABLED',
});

export type FeatureEnvKey = (typeof FEATURE_ENV_KEYS)[keyof typeof FEATURE_ENV_KEYS];
