import { z } from 'zod';
export declare const DirectSessionsProviderIdSchema: any;
export type DirectSessionsProviderId = z.infer<typeof DirectSessionsProviderIdSchema>;
export declare const DirectSessionsSourceSchema: any;
export type DirectSessionsSource = z.infer<typeof DirectSessionsSourceSchema>;
export declare const DirectSessionsSearchModeSchema: any;
export type DirectSessionsSearchMode = z.infer<typeof DirectSessionsSearchModeSchema>;
export declare const DirectSessionsCandidatesListRequestSchema: any;
export type DirectSessionsCandidatesListRequest = z.infer<typeof DirectSessionsCandidatesListRequestSchema>;
export declare const DirectSessionsCandidatesListResponseSchema: any;
export type DirectSessionsCandidatesListResponse = z.infer<typeof DirectSessionsCandidatesListResponseSchema>;
export declare const DirectSessionLinkEnsureRequestSchema: any;
export type DirectSessionLinkEnsureRequest = z.infer<typeof DirectSessionLinkEnsureRequestSchema>;
export declare const DirectSessionLinkEnsureResponseSchema: any;
export type DirectSessionLinkEnsureResponse = z.infer<typeof DirectSessionLinkEnsureResponseSchema>;
export declare const DirectSessionActivityV1Schema: any;
export type DirectSessionActivityV1 = z.infer<typeof DirectSessionActivityV1Schema>;
export declare const DirectSessionCandidateV1Schema: any;
export type DirectSessionCandidateV1 = z.infer<typeof DirectSessionCandidateV1Schema>;
export declare const DirectSessionStatusGetRequestSchema: any;
export type DirectSessionStatusGetRequest = z.infer<typeof DirectSessionStatusGetRequestSchema>;
export declare const DirectSessionAttachRequestSchema: any;
export type DirectSessionAttachRequest = z.infer<typeof DirectSessionAttachRequestSchema>;
export declare const DirectSessionAttachResponseSchema: any;
export type DirectSessionAttachResponse = z.infer<typeof DirectSessionAttachResponseSchema>;
export declare const DirectSessionDetachRequestSchema: any;
export type DirectSessionDetachRequest = z.infer<typeof DirectSessionDetachRequestSchema>;
export declare const DirectSessionDetachResponseSchema: any;
export type DirectSessionDetachResponse = z.infer<typeof DirectSessionDetachResponseSchema>;
export declare const DirectSessionFollowPolicySetRequestSchema: any;
export type DirectSessionFollowPolicySetRequest = z.infer<typeof DirectSessionFollowPolicySetRequestSchema>;
export declare const DirectSessionFollowPolicySetResponseSchema: any;
export type DirectSessionFollowPolicySetResponse = z.infer<typeof DirectSessionFollowPolicySetResponseSchema>;
export declare const DirectSessionStatusGetResponseSchema: any;
export type DirectSessionStatusGetResponse = z.infer<typeof DirectSessionStatusGetResponseSchema>;
export declare const DirectTranscriptRawMessageV1Schema: any;
export type DirectTranscriptRawMessageV1 = z.infer<typeof DirectTranscriptRawMessageV1Schema>;
export declare const DirectTranscriptPageRequestSchema: any;
export type DirectTranscriptPageRequest = z.infer<typeof DirectTranscriptPageRequestSchema>;
export declare const DirectTranscriptPageResponseSchema: any;
export type DirectTranscriptPageResponse = z.infer<typeof DirectTranscriptPageResponseSchema>;
export declare const DirectTranscriptReadAfterRequestSchema: any;
export type DirectTranscriptReadAfterRequest = z.infer<typeof DirectTranscriptReadAfterRequestSchema>;
export declare const DirectTranscriptReadAfterResponseSchema: any;
export type DirectTranscriptReadAfterResponse = z.infer<typeof DirectTranscriptReadAfterResponseSchema>;
export declare const DirectSessionTakeoverRequestSchema: any;
export type DirectSessionTakeoverRequest = z.infer<typeof DirectSessionTakeoverRequestSchema>;
export declare const DirectSessionTakeoverResponseSchema: any;
export type DirectSessionTakeoverResponse = z.infer<typeof DirectSessionTakeoverResponseSchema>;
export declare const DirectSessionTakeoverPersistRequestSchema: any;
export type DirectSessionTakeoverPersistRequest = z.infer<typeof DirectSessionTakeoverPersistRequestSchema>;
export declare const DirectSessionTakeoverPersistResponseSchema: any;
export type DirectSessionTakeoverPersistResponse = z.infer<typeof DirectSessionTakeoverPersistResponseSchema>;
//# sourceMappingURL=daemonRpcV1.d.ts.map